services:
  - type: static
    name: jendyco-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: build
    rootDir: frontend
    routes:
      - type: rewrite
        source: /.*
        destination: /index.html
